import { PlusOutlined } from '@ant-design/icons'
import { Button,Form,Input,Modal,Select,Space,Table,Tag,Typography,message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect,useMemo,useState } from 'react'
import { api,apiErrorMessage } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import UserRoleEditor from '../features/users/UserRoleEditor'
import AccountLockActions from '../features/users/AccountLockActions'
import type { RoleDetail,UserItem } from '../types'
const DRAFT_KEY='draft:user-management'
const statusMap:Record<string,{color:string;label:string}>={active:{color:'green',label:'Hoạt động'},pending:{color:'gold',label:'Chờ kích hoạt'},locked:{color:'red',label:'Đã khóa'}}
export default function UserManagementPage(){
 const {hasPermission}=useAuth();const [users,setUsers]=useState<UserItem[]>([]);const [roles,setRoles]=useState<RoleDetail[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [q,setQ]=useState('');const [role,setRole]=useState<string>();const [status,setStatus]=useState<string>();const [loading,setLoading]=useState(false);const [editUser,setEditUser]=useState<UserItem|null>(null);const [open,setOpen]=useState(false);const [form]=Form.useForm()
 const loadRoles=async()=>{if(!hasPermission('roles.view'))return;const r=await api.get('/api/roles');setRoles(r.data.roles)}
 const loadUsers=async()=>{setLoading(true);try{const r=await api.get('/api/users',{params:{q:q||undefined,role,status,page,page_size:20}});setUsers(r.data.items);setTotal(r.data.total)}catch(e){message.error(apiErrorMessage(e))}finally{setLoading(false)}}
 useEffect(()=>{loadRoles().catch(()=>undefined)},[]) // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{loadUsers()},[page,role,status,q]) // eslint-disable-line react-hooks/exhaustive-deps
 const openCreate=()=>{setEditUser(null);form.resetFields();const draft=sessionStorage.getItem(DRAFT_KEY);if(draft){try{form.setFieldsValue(JSON.parse(draft))}catch{}}setOpen(true)}
 const openEdit=(u:UserItem)=>{setEditUser(u);form.setFieldsValue({full_name:u.full_name,email:u.email,phone:u.phone});setOpen(true)}
 const save=async()=>{try{const v=await form.validateFields();if(editUser){await api.put(`/api/users/${editUser.id}`,{full_name:v.full_name,email:v.email,phone:v.phone||null});message.success('Đã cập nhật người dùng')}else{const r=await api.post('/api/users',{...v,role_slugs:v.role_slugs||['student']});message.success(`Đã tạo tài khoản.${r.data.debug_temporary_password?` Mật khẩu tạm (dev): ${r.data.debug_temporary_password}`:''}`,8);sessionStorage.removeItem(DRAFT_KEY)}setOpen(false);await loadUsers()}catch(e){if((e as {errorFields?:unknown}).errorFields)return;message.error(apiErrorMessage(e))}}
 const columns=useMemo<ColumnsType<UserItem>>(()=>[
 {title:'Họ tên',dataIndex:'full_name',render:(v)=><strong>{v}</strong>},{title:'Email',dataIndex:'email'},{title:'Điện thoại',dataIndex:'phone',responsive:['md']},{title:'Vai trò',render:(_,r)=><Space wrap>{r.roles.map(x=><Tag key={x.slug}>{x.name}</Tag>)}</Space>},{title:'Trạng thái',dataIndex:'status',render:(v)=><Tag color={statusMap[v]?.color}>{statusMap[v]?.label||v}</Tag>},{title:'Thao tác',fixed:'right',render:(_,r)=><Space wrap>{hasPermission('users.update')&&<Button size="small" onClick={()=>openEdit(r)}>Sửa</Button>}<UserRoleEditor _user={r} _roles={roles} onSaved={loadUsers}/><AccountLockActions _user={r} onSaved={loadUsers}/></Space>}
 ],[hasPermission,roles])
 return <div className="page-wrap"><div className="page-title-row"><div><Typography.Title level={2}>Quản lý người dùng</Typography.Title><Typography.Text type="secondary">Tìm theo tên, email, số điện thoại; lọc theo vai trò và trạng thái.</Typography.Text></div>{hasPermission('users.create')&&<Button type="primary" icon={<PlusOutlined/>} onClick={openCreate}>Tạo tài khoản</Button>}</div><Space wrap className="toolbar"><Input.Search placeholder="Tên, email hoặc số điện thoại" allowClear style={{width:300}} onSearch={v=>{setQ(v);setPage(1)}}/><Select allowClear placeholder="Vai trò" style={{minWidth:180}} options={roles.map(r=>({label:r.name,value:r.slug}))} onChange={v=>{setRole(v);setPage(1)}}/><Select allowClear placeholder="Trạng thái" style={{minWidth:160}} options={[{value:'active',label:'Hoạt động'},{value:'pending',label:'Chờ kích hoạt'},{value:'locked',label:'Đã khóa'}]} onChange={v=>{setStatus(v);setPage(1)}}/><Button onClick={loadUsers}>Làm mới</Button></Space><Table rowKey="id" loading={loading} columns={columns} dataSource={users} scroll={{x:900}} pagination={{current:page,pageSize:20,total,showSizeChanger:false,onChange:setPage}}/><Modal title={editUser?'Cập nhật người dùng':'Tạo tài khoản'} open={open} onCancel={()=>setOpen(false)} onOk={save}><Form form={form} layout="vertical" onValuesChange={(_,all)=>{if(!editUser)sessionStorage.setItem(DRAFT_KEY,JSON.stringify(all))}}><Form.Item name="full_name" label="Họ tên" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="email" label="Email" rules={[{required:true},{type:'email'}]}><Input/></Form.Item><Form.Item name="phone" label="Số điện thoại"><Input/></Form.Item>{!editUser&&<Form.Item name="role_slugs" label="Vai trò" initialValue={['student']}><Select mode="multiple" options={roles.map(r=>({label:r.name,value:r.slug}))}/></Form.Item>}</Form></Modal></div>
}
